### ISSUE TITLE
Graphic problems in top gear 3000

### ISSUE THREAD

**Issue by marleyap** [libretro/Lakka-LibreELEC#160]
Hello, I'm having graphics problems in top gear 3000, which is, glitchs in cars and scenarios.
I use the version Lakka OS 2.1 RC2 PC version, core emulator is Snes9x 1.54.117054ee, my machine is an HP pavilion g4-2017-br with AMD dual-core A6-4400m, 6gb ram. Please correct this problem, thank you!

**Comment by Kivutar** [comment]
Can you try to switch either to
  * Lakka 2.1-rc3 that I published yesterday night and has an updated version of snes9x 
  * bsnes mercury for the core

**Comment by marleyap** [comment]
I tested the newer versions of the Snes9X libretto Lakka OS 2.1 rc3, but the bugs in the scenarios and cars still happen, and have a detail the official version of Snes9x this bug does not happen, maybe it is programming error from core snes9x to retroarch, until The version for windows has this same problem, this has to be repaired as soon as possible. And the Bsnes Mercury the problem is worse !!!  Thank you very much in advance!

**Comment by Kivutar** [comment]
I'm surprised because bsnes is known as a super accurate core.
You're using a no-intro rom?

**Comment by marleyap** [comment]
I use bsnes balanced mercury, now I do not know if it's the emulator's own problem or dsp-4 firmware that I use to run the top gear 3000.

**Comment by marleyap** [comment]
Use to rom top gear 3000 clean

**Comment by Ntemis** [comment]
Can we have your gpu?

**Comment by marleyap** [comment]
Not really a gpu is an apu, it is dual core cpu with radeon HD 7520g .... my notebook is an hp pavilion g4- 2117br, and all games that use the chips dsp1,2,3 and 4 are showing bugs in Core bsnes accurate, bsnes balanced and bsnes performance and also in the mercury versions. In snes9x only top gear 3000 is presenting graphical flaws and others that use the other variations of the dsp chips are working normal and being this bug in top gear 3000 only in the versions snes9x core retroarch, these bugs happen in both the windows, linux, but platforms I do not know if these problems happen in android and etc, but in the official version snes9x and higan / bsnes works perfect.

**Comment by marleyap** [comment]
![super mario kart usa -170704-175147](https://user-images.githubusercontent.com/29718783/27839552-7e17bc96-60c8-11e7-9765-f7377bf59626.png)
![top gear 3000 usa -170704-175053](https://user-images.githubusercontent.com/29718783/27839551-7dca5550-60c8-11e7-8119-257e3900079d.png)
Graphical errors in all bsnes versions '' normal '' and bsnes mercury, except in the bsnes mednafen version

**Comment by marleyap** [comment]
![top gear 3000 usa -170704-175909](https://user-images.githubusercontent.com/29718783/27839695-a9adc7f0-60c9-11e7-8d25-6a4d76db4b4f.png)

And this is the graphical errors that happen in the snes9x retroarch core ... and that's it, but finally I hope they solve those problems.

**Comment by Kivutar** [comment]
I think we should move this bug report to the repositories of snes9x and bsnes. But I still can't understand why the bug happens on both emulators.

**Comment by kunfuchicken** [comment]
Hi, all my other snes games are running through bsnes mercury accurate just fine, but top gear 3000 wont even load. I get the message "Failed to load Content." I've tried other cores, still nothing. I can't seem to figure out the problem. Any ideas?

**Comment by Ntemis** [comment]
Then lets call @twinaphex to share some light 👍

**Comment by ToKe79** [comment]
stale
