### ISSUE TITLE
Build linux:host fails Lunar Lobster

### ISSUE THREAD

**Issue by therevtanker2100** [libretro/Lakka-LibreELEC#1868]
This issue tracker is NOT for help or support. Please use one of the following channels for help and support:
- the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general)
- via IRC @ #lakkatv on freenode.net
- #lakkatv on libretro discord https://discord.gg/retroarch

Before you report a bug make sure you have tried the latest nightly version of Lakka at https://nightly.builds.lakka.tv/latest/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- 5.xx
- B550M-C
- Compile the source code
- Failure from something like this "https://codeload.github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/tar.gz/refs/tags/microcode-20230613" ""
- Error patching makefile even manually doing it is a fail
`[1;36mGET[0m      linux (archive)
--2023-07-22 22:17:26--  https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.1.38.tar.xz
Resolving www.kernel.org (www.kernel.org)... 2604:1380:4641:c500::1, 139.178.84.217
Connecting to www.kernel.org (www.kernel.org)|2604:1380:4641:c500::1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.1.38.tar.xz [following]
--2023-07-22 22:17:26--  https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.1.38.tar.xz
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 2604:1380:45d1:ec00::1, 147.75.199.223
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|2604:1380:45d1:ec00::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 134926628 (129M) [application/x-xz]
Saving to: '/home/dmdomnic/Downloads/Lakka-LibreELEC/sources/linux/linux-6.1.38.tar.xz'

          /home/dmd   0%[                    ]       0  --.-KB/s               
         /home/dmdo   0%[                    ] 343.61K  1.48MB/s               
        /home/dmdom   1%[                    ]   2.32M  5.44MB/s               
       /home/dmdomn   3%[                    ]   4.77M  7.60MB/s               
      /home/dmdomni   5%[>                   ]   6.63M  7.97MB/s               
     /home/dmdomnic   7%[>                   ]   9.07M  8.79MB/s               
    /home/dmdomnic/   9%[>                   ]  11.82M  9.56MB/s               
   /home/dmdomnic/D  11%[=>                  ]  14.44M  10.0MB/s               
  /home/dmdomnic/Do  13%[=>                  ]  17.24M  10.5MB/s               
 /home/dmdomnic/Dow  15%[==>                 ]  19.85M  10.8MB/s               
/home/dmdomnic/Down  17%[==>                 ]  22.46M  11.0MB/s               
home/dmdomnic/Downl  19%[==>                 ]  24.93M  11.1MB/s               
ome/dmdomnic/Downlo  21%[===>                ]  27.30M  11.1MB/s               
me/dmdomnic/Downloa  23%[===>                ]  29.71M  11.2MB/s               
e/dmdomnic/Download  24%[===>                ]  31.96M  11.2MB/s               
/dmdomnic/Downloads  26%[====>               ]  34.27M  11.2MB/s    eta 8s     
dmdomnic/Downloads/  28%[====>               ]  36.54M  11.8MB/s    eta 8s     
mdomnic/Downloads/L  30%[=====>              ]  38.81M  12.0MB/s    eta 8s     
domnic/Downloads/La  31%[=====>              ]  40.96M  11.9MB/s    eta 8s     
omnic/Downloads/Lak  33%[=====>              ]  43.24M  12.0MB/s    eta 8s     
mnic/Downloads/Lakk  35%[======>             ]  45.82M  12.2MB/s    eta 7s     
nic/Downloads/Lakka  37%[======>             ]  48.08M  12.1MB/s    eta 7s     
ic/Downloads/Lakka-  39%[======>             ]  50.46M  11.9MB/s    eta 7s     
c/Downloads/Lakka-L  41%[=======>            ]  52.83M  11.9MB/s    eta 7s     
/Downloads/Lakka-Li  42%[=======>            ]  55.29M  11.8MB/s    eta 7s     
Downloads/Lakka-Lib  44%[=======>            ]  57.76M  11.7MB/s    eta 6s     
ownloads/Lakka-Libr  46%[========>           ]  59.68M  11.6MB/s    eta 6s     
wnloads/Lakka-Libre  47%[========>           ]  61.73M  11.4MB/s    eta 6s     
nloads/Lakka-LibreE  49%[========>           ]  63.60M  11.2MB/s    eta 6s     
loads/Lakka-LibreEL  51%[=========>          ]  65.66M  11.2MB/s    eta 6s     
oads/Lakka-LibreELE  52%[=========>          ]  67.73M  11.1MB/s    eta 5s     
ads/Lakka-LibreELEC  54%[=========>          ]  69.73M  11.0MB/s    eta 5s     
ds/Lakka-LibreELEC/  55%[==========>         ]  71.63M  10.9MB/s    eta 5s     
s/Lakka-LibreELEC/s  57%[==========>         ]  73.87M  10.9MB/s    eta 5s     
/Lakka-LibreELEC/so  59%[==========>         ]  76.27M  11.0MB/s    eta 5s     
Lakka-LibreELEC/sou  61%[===========>        ]  78.52M  10.9MB/s    eta 5s     
akka-LibreELEC/sour  62%[===========>        ]  80.68M  10.8MB/s    eta 5s     
kka-LibreELEC/sourc  64%[===========>        ]  82.94M  10.8MB/s    eta 5s     
ka-LibreELEC/source  66%[============>       ]  85.02M  10.7MB/s    eta 5s     
a-LibreELEC/sources  67%[============>       ]  87.29M  10.6MB/s    eta 5s     
-LibreELEC/sources/  69%[============>       ]  89.21M  10.4MB/s    eta 4s     
LibreELEC/sources/l  70%[=============>      ]  91.29M  10.4MB/s    eta 4s     
ibreELEC/sources/li  72%[=============>      ]  93.46M  10.5MB/s    eta 4s     
breELEC/sources/lin  74%[=============>      ]  95.46M  10.5MB/s    eta 4s     
reELEC/sources/linu  75%[==============>     ]  97.52M  10.5MB/s    eta 4s     
eELEC/sources/linux  77%[==============>     ]  99.58M  10.5MB/s    eta 3s     
ELEC/sources/linux/  79%[==============>     ] 101.71M  10.6MB/s    eta 3s     
LEC/sources/linux/l  80%[===============>    ] 103.69M  10.6MB/s    eta 3s     
EC/sources/linux/li  82%[===============>    ] 105.65M  10.5MB/s    eta 3s     
C/sources/linux/lin  83%[===============>    ] 107.60M  10.4MB/s    eta 3s     
/sources/linux/linu  85%[================>   ] 109.93M  10.4MB/s    eta 2s     
sources/linux/linux  87%[================>   ] 112.35M  10.5MB/s    eta 2s     
ources/linux/linux-  89%[================>   ] 114.83M  10.5MB/s    eta 2s     
urces/linux/linux-6  91%[=================>  ] 117.48M  10.7MB/s    eta 2s     
rces/linux/linux-6.  93%[=================>  ] 119.80M  10.7MB/s    eta 2s     
ces/linux/linux-6.1  94%[=================>  ] 122.10M  10.9MB/s    eta 1s     
es/linux/linux-6.1.  96%[==================> ] 124.30M  10.9MB/s    eta 1s     
s/linux/linux-6.1.3  98%[==================> ] 126.79M  11.0MB/s    eta 1s     
/home/dmdomnic/Down 100%[===================>] 128.68M  11.1MB/s    in 12s     

2023-07-22 22:17:39 (11.0 MB/s) - '/home/dmdomnic/Downloads/Lakka-LibreELEC/sources/linux/linux-6.1.38.tar.xz' saved [134926628/134926628]

    [1;32mINFO[0m      Calculated checksum: f9a4f91b609f7d332a5f2be01ab86336fa00149fae6bdc19f16fa19f78802d43
[1;36mGET[0m      intel-ucode (archive)
--2023-07-22 22:17:39--  https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/archive/microcode-20230613.tar.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/tar.gz/refs/tags/microcode-20230613 [following]
--2023-07-22 22:17:40--  https://codeload.github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/tar.gz/refs/tags/microcode-20230613
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/home/dmdomnic/Downloads/Lakka-LibreELEC/sources/intel-ucode/intel-ucode-20230613.tar.gz'

          /home/dmd     [<=>                 ]       0  --.-KB/s               
         /home/dmdo     [ <=>                ] 165.35K   781KB/s               
        /home/dmdom     [  <=>               ] 903.53K  2.13MB/s               
       /home/dmdomn     [   <=>              ]   1.77M  2.89MB/s               
      /home/dmdomni     [    <=>             ]   2.68M  3.28MB/s               
     /home/dmdomnic     [     <=>            ]   3.53M  3.48MB/s               
    /home/dmdomnic/     [      <=>           ]   4.55M  3.74MB/s               
   /home/dmdomnic/D     [       <=>          ]   5.66M  3.96MB/s               
  /home/dmdomnic/Do     [        <=>         ]   6.64M  4.07MB/s               
 /home/dmdomnic/Dow     [         <=>        ]   7.70M  4.21MB/s               
/home/dmdomnic/Down     [          <=>       ]   8.81M  4.33MB/s               
home/dmdomnic/Downl     [           <=>      ]   9.81M  4.39MB/s               
ome/dmdomnic/Downlo     [            <=>     ]  10.84M  4.45MB/s               
/home/dmdomnic/Down     [             <=>    ]  11.77M  4.50MB/s    in 2.6s    

2023-07-22 22:17:43 (4.50 MB/s) - '/home/dmdomnic/Downloads/Lakka-LibreELEC/sources/intel-ucode/intel-ucode-20230613.tar.gz' saved [12338446]

    [1;32mINFO[0m      Calculated checksum: 894d822d2347222a2595d4fc47d358e01d35a54780123100c317dfc31b1b0cc9
[1;36mUNPACK[0m      intel-ucode
[1;36mUNPACK[0m      linux
    [1;32mAPPLY PATCH [1;37m(common - default)[0m[0m      packages/linux/patches/default/0005-ithc.patch
patching file drivers/iommu/intel/irq_remapping.c
patching file drivers/hid/Kconfig
Hunk #1 succeeded at 1290 with fuzz 2 (offset -2 lines).
patching file drivers/hid/Makefile
Hunk #1 FAILED at 166.
1 out of 1 hunk FAILED -- saving rejects to file drivers/hid/Makefile.rej
patching file drivers/hid/ithc/Kbuild
patching file drivers/hid/ithc/Kconfig
patching file drivers/hid/ithc/ithc-debug.c
patching file drivers/hid/ithc/ithc-dma.c
patching file drivers/hid/ithc/ithc-dma.h
patching file drivers/hid/ithc/ithc-main.c
patching file drivers/hid/ithc/ithc-regs.c
patching file drivers/hid/ithc/ithc-regs.h
patching file drivers/hid/ithc/ithc.h
*********** FAILED COMMAND ***********
patch -d "${PKG_BUILD}" -p1 < ${i} >&${VERBOSE_OUT}
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
[1;31mFAILURE: scripts/build linux:host has failed![0m`

**Comment by Ntemis** [comment]
Thanks for the report , the patch was recently added for trial purposes as supposedly should be compatible with our 6.1 kernel. I will remove it soon

**Comment by therevtanker2100** [comment]
Will there be the package nvidia-driver-535 implementation on Lakka 6.1? Or can I include it myself?

**Comment by Ntemis** [comment]
issue should be fixed, check and close

**Comment by therevtanker2100** [comment]
Nope isn't resolved
`--2023-07-24 18:57:54--  https://sources.libreelec.tv/mirror/nasm/nasm-2.16.01.tar.xz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-24 18:57:54 ERROR 404: Not Found.


Cannot get nasm sources : https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz
Try later!
*********** FAILED COMMAND ***********
. "${get_handler}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/get "${PKG_NAME}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/build nasm:host has failed!

The following log for this failure is available:
  /home/dmdomnic/Downloads/Lakka-LibreELEC/build.Lakka-Generic.x86_64-5.0-devel/.threads/logs/34.log

>>> nasm:host seq 34 >>>
[143/412] [FAIL] build   nasm:host

The following log for this failure is available:
  /home/dmdomnic/Downloads/Lakka-LibreELEC/build.Lakka-Generic.x86_64-5.0-devel/.threads/logs/34.log

Parallel build failure - see log for details. Time of failure: Mon Jul 24 18:57:54 CDT 2023
make: *** [Makefile:10: image] Error 1
`
Now it's mentioning the ecwolf missing

**Comment by RobokingsCosmos** [comment]
I'll close and say that it's still not fixed on ecwolf after reinstallation and recompilation.

**Comment by therevtanker2100** [comment]
I'll close and say that it's still not fixed on ecwolf after reinstallation and recompilation.
